live_config_reload = true

[colors.bright]
black = "0x7f8c8d"
blue = "0x3daee9"
cyan = "0x16a085"
green = "0x1cdc9a"
magenta = "0x8e44ad"
red = "0xc0392b"
white = "0xffffff"
yellow = "0xfdbc4b"

[colors.dim]
black = "0x31363b"
blue = "0x1b668f"
cyan = "0x186c60"
green = "0x17a262"
magenta = "0x614a73"
red = "0x783228"
white = "0x63686d"
yellow = "0xb65619"

[colors.normal]
black = "0x232627"
blue = "0x1d99f3"
cyan = "0x1abc9c"
green = "0x11d116"
magenta = "0x9b59b6"
red = "0xed1515"
white = "0xfcfcfc"
yellow = "0xf67400"

[colors.primary]
background = "0x232627"
bright_foreground = "0xffffff"
dim_foreground = "0xeff0f1"
foreground = "0xfcfcfc"

[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[scrolling]
history = 1000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t@="

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
opacity = 0.8
title = "Alacritty"

[window.padding]
x = 50
y = 50
